/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package EstruturasCondicionais;

import java.util.Scanner;

public class App {

    public static void main(String[] args) {
        
        Scanner leitor = new Scanner(System.in);
        
        System.out.println("Digite sua nota");
        
        int nota = leitor.nextInt();
        
        if(nota >= 7){
            if(nota == 10){
                System.out.println("Parabéns, você foi aprovado com nota máxima");
            } else {
                System.out.println("Parabéns, você foi aprovado");
            }
        } else {
            System.out.println("Você foi reprovado com nota " + nota);
        }
    }
}
